### ISSUE TITLE
HTML preview: support volumes

### ISSUE THREAD

**Issue by josteinaj** [snaekobbi/issues#27] opened 2016-03-31 10:42 UTC

**Comment by bertfrees** [comment] 2016-04-04 15:31
Yep, I've been looking into this but haven't found the time yet. This is quite important indeed.

**Comment by bertfrees** [comment] 2016-11-17 13:25
Duplicate of https://github.com/daisy/pipeline-mod-braille/issues/87. This was fixed in https://github.com/daisy/pipeline-mod-braille/commit/9639e36102b1768ddfcbc1f44c1adaafe4a5ad3e.

**Closed as completed** 2016-11-17 15:04 UTC
Labels: duplicate, enhancement
